name: portfolio
description: "Minimal & clean portfolio"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  url_launcher: ^6.1.10
  font_awesome_flutter: ^10.12.0
  google_fonts: ^6.3.2
  visibility_detector: ^0.4.0+2
  sizer: ^3.1.3
  lucide_icons: ^0.257.0
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: false
  ios: false
  web:
    generate: true
    image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/resume.pdf
